# Generated by Django 6.1.1 on 2026-09-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
